version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:

  # create_infrastructure: 
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - add_ssh_keys:
  #         fingerprints: ["10:4b:1a:d5:55:83:83:74:21:99:e4:c9:51:f6:fa:84"]
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy --template-file ec2-aws.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1 

  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["3d:0a:52:80:0c:0b:88:56:fd:94:3b:76:2c:c3:7a:63"] 
      - run:
          name: Install Ansible
          command: |
            akp add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i hosts playbook.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - configure_infrastructure 




